
general = {
  name = "OpenWrt-AirPlay";
  audio_backend_latency_offset_in_seconds = -1.1;
  audio_backend_buffer_desired_length_in_seconds = 0.08;
 // run_this_before_play_begins = "/usr/bin/airplay-vol-lock.sh";

};
diagnostics = {
  log_verbosity = 1;
};
alsa = {
  output_device = "default";
  disable_mmap = true;
};
audio = {
  output_format = "S16";
  playback_mode = "stereo";
  output_rate = 48000;
  interpolation = "soxr";
};
latency = {
  initial = 260;
  default = 260;
  maximum = 500;
};
resync = {
  threshold = 0.004;
};
drift_tolerance_in_seconds = 0.001;
sessioncontrol = {
  allow_session_interruption = true;
};
